#!/bin/sh

set -e

GROUP='stratio'
USER='stratio'
DIR_INSTALL='/opt/sds/stratio-connector-sparksql'
DIR_CONF='/etc/sds/stratio-connector-sparksql'
DIR_LOG='/var/log/sds/stratio-connector-sparksql'

case "$1" in
  configure)

  # Add stratio group if it doesn't already exists
  if ! getent group $GROUP >/dev/null 2>&1; then
    groupadd ${GROUP} 
  fi

  # Add stratio user if it doesn't already exists
  if ! getent passwd $USER >/dev/null 2>&1; then
    [ -d /opt ] || mkdir /opt
    useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
  else
    usermod -G $GROUP $USER
  fi

  if [! -d "$DIR_LOG" ]; then
   mkdir $DIR_LOG
  fi

  chown -R ${USER}:${GROUP} /opt/sds /etc/sds
  chown root:root /etc/init.d/stratio-connector-sparksql
 
  chown -R ${USER}:${GROUP} $DIR_INSTALL
  chown -R ${USER}:${GROUP} $DIR_CONF
  chown -R ${USER}:${GROUP} $DIR_LOG
  chmod 775 $DIR_INSTALL
  chmod 775 $DIR_CONF
  chmod 775 $DIR_LOG
  
  update-rc.d stratio-connector-sparksql defaults

  ;;
esac
cp /opt/sds/stratio-connector-sparksql/bin/stratio-connector-sparksql-* /opt/sds/stratio-connector-sparksql/bin/stratio-connector-sparksql
cp /opt/sds/stratio-connector-sparksql/template/SparkSQLConnector /etc/init.d/stratio-connector-sparksql
chmod 755 /etc/init.d/stratio-connector-sparksql
chmod 755 /opt/sds/stratio-connector-sparksql/bin/stratio-connector-sparksql
chmod +x /etc/default/stratio-connector-sparksql
export SPARKSQL_CONNECTOR_LIB=/opt/sds/stratio-connector-sparksql/
export SPARKSQL_CONNECTOR_CONF="/etc/sds/stratio-connector-sparksql"


exit 0

